[build]
  command = "pnpm install --frozen-lockfile && pnpm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22.17.0"
  PNPM_VERSION = "9.14.4"
  NPM_FLAGS = "--version"
  NODE_OPTIONS = "--max-old-space-size=4096"
  # 注意：敏感的环境变量应该在Netlify控制台中设置，而不是在这里

# 启用 PNPM
[build.processing]
  skip_processing = false

# 函数配置
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp"]

# 重定向规则 - API路由
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# 重定向规则 - 404页面处理
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# 缓存配置 - 静态资源
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API缓存配置
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "public, max-age=300"
    Access-Control-Allow-Origin = "*"